-- Generated by scripts/generate_catalog_seed.py — DO NOT EDIT BY HAND.
-- Source of truth: js/catalog.js (LOCAL_PRODUCTS).
-- Idempotent: safe to re-run; updates the canonical rows by name.

insert into public.products
  (id, dept, collection, name, description, price_ghs, compare_at_ghs, flash_sale,
   sizes, colors, badge, in_stock, sort_order, image)
overriding system value
values
  (1, 'fashion', 'streetwear', 'Brooklyn Crop Set', 'A soft two-piece crop top and joggers set for easy street days.', 180, 230, true, array['XS', 'S', 'M', 'L', 'XL'], array['Black', 'White'], 'Flash sale', true, 1, 'assets/products/fashion-crop-set.jpg'),
  (2, 'fashion', 'streetwear', 'Oversized Navy Tee', 'An oversized cotton tee in navy. Everyday wear, nothing extra.', 150, 200, true, array['XS', 'S', 'M', 'L', 'XL'], array['Royal Navy', 'White', 'Black'], 'Flash sale', true, 2, 'assets/products/fashion-royal-tee.jpg'),
  (3, 'fashion', 'modest', 'Modest Satin Maxi Dress', 'A relaxed satin maxi dress with long sleeves, made to move with you.', 260, null, false, array['XS', 'S', 'M', 'L', 'XL'], array['Emerald', 'Navy', 'Burgundy'], null, true, 3, 'assets/products/fashion-modest-maxi.jpg'),
  (4, 'fashion', 'modest', 'Everyday Modest Set', 'A long-line top and wide trousers set. Comfortable and easy to style.', 220, null, false, array['XS', 'S', 'M', 'L', 'XL'], array['Beige', 'Navy'], null, true, 4, 'assets/products/fashion-modest-set.jpg'),
  (15, 'fashion', 'modest', 'Ivory Wrap Dress', 'A soft ivory wrap dress with a flattering tie waist. Easy to dress up or down.', 240, null, false, array['XS', 'S', 'M', 'L', 'XL'], array['Ivory'], null, true, 15, 'assets/products/fashion-ivory-wrap-dress.jpg'),
  (16, 'fashion', 'streetwear', 'Navy Wide-Leg Trousers', 'High-waist navy trousers with a relaxed wide leg. A polished streetwear staple.', 160, 200, true, array['XS', 'S', 'M', 'L', 'XL'], array['Navy'], 'Flash sale', true, 16, 'assets/products/fashion-wide-leg-trousers.jpg'),
  (17, 'fashion', 'streetwear', 'Burgundy Pleated Skirt', 'A modern burgundy pleated midi skirt with a soft movement.', 150, 170, true, array['XS', 'S', 'M', 'L'], array['Burgundy'], 'Flash sale', true, 17, 'assets/products/fashion-pleated-skirt.jpg');

on conflict (name) do update set
  dept = excluded.dept,
  collection = excluded.collection,
  description = excluded.description,
  price_ghs = excluded.price_ghs,
  compare_at_ghs = excluded.compare_at_ghs,
  flash_sale = excluded.flash_sale,
  sizes = excluded.sizes,
  colors = excluded.colors,
  badge = excluded.badge,
  in_stock = excluded.in_stock,
  sort_order = excluded.sort_order,
  image = excluded.image;

-- Keep the identity sequence ahead of the explicit ids above.
select setval(
  pg_get_serial_sequence('public.products', 'id'),
  coalesce((select max(id) from public.products), 1)
);
