#!/usr/bin/env python3
"""Generate supabase/catalog-seed.sql from js/catalog.js.

js/catalog.js (LOCAL_PRODUCTS) is the single source of truth for the
catalog. This script renders it as idempotent SQL upserts so the database
seed cannot drift from the storefront fallback data.

Usage:
  python3 scripts/generate_catalog_seed.py           # (re)write the seed file
  python3 scripts/generate_catalog_seed.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

# build-seo.py has a hyphen in its name; load it by path instead of import.
_SPEC = importlib.util.spec_from_file_location(
    "build_seo", Path(__file__).resolve().parent / "build-seo.py"
)
build_seo = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(build_seo)

ROOT = build_seo.ROOT
load_products = build_seo.load_products

SEED_PATH = ROOT / "supabase" / "catalog-seed.sql"

CANONICAL_NAMES = [
    "Brooklyn Crop Set",
    "Oversized Navy Tee",
    "Modest Satin Maxi Dress",
    "Everyday Modest Set",
    "Ivory Wrap Dress",
    "Navy Wide-Leg Trousers",
    "Burgundy Pleated Skirt",
]


def sql_quote(value) -> str:
    if value is None:
        return "null"
    text = str(value)
    return "'" + text.replace("'", "''") + "'"


def sql_number(value) -> str:
    if value is None:
        return "null"
    number = float(value)
    return str(int(number)) if number.is_integer() else repr(number)


def sql_bool(value) -> str:
    return "true" if value else "false"


def sql_text_array(values) -> str:
    if not values:
        return "array[]::text[]"
    inner = ", ".join(sql_quote(v) for v in values)
    return f"array[{inner}]"


def render_seed() -> str:
    products = load_products()
    names = [p["name"] for p in products]
    if sorted(names) != sorted(CANONICAL_NAMES):
        raise SystemExit(
            "catalog.js no longer matches the canonical 7-product catalog.\n"
            f"  catalog.js : {sorted(names)}\n"
            f"  expected   : {sorted(CANONICAL_NAMES)}\n"
            "Update CANONICAL_NAMES in this script AND the dated migration if the "
            "catalog change is intentional."
        )

    lines = [
        "-- Generated by scripts/generate_catalog_seed.py — DO NOT EDIT BY HAND.",
        "-- Source of truth: js/catalog.js (LOCAL_PRODUCTS).",
        "-- Idempotent: safe to re-run; updates the canonical rows by name.",
        "",
        "insert into public.products",
        "  (id, dept, collection, name, description, price_ghs, compare_at_ghs, flash_sale,",
        "   sizes, colors, badge, in_stock, sort_order, image)",
        "overriding system value",
        "values",
    ]
    for i, p in enumerate(products):
        values = ", ".join(
            [
                sql_number(p["id"]),
                sql_quote(p["dept"]),
                sql_quote(p.get("collection")),
                sql_quote(p["name"]),
                sql_quote(p.get("description")),
                sql_number(p["price_ghs"]),
                sql_number(p.get("compare_at_ghs")),
                sql_bool(p.get("flash_sale") is True),
                sql_text_array(p.get("sizes") or []),
                sql_text_array(p.get("colors") or []),
                sql_quote(p.get("badge")),
                sql_bool(p.get("in_stock", True)),
                sql_number(p.get("sort_order") or 0),
                sql_quote(p.get("image")),
            ]
        )
        lines.append(f"  ({values})" + ("," if i < len(products) - 1 else ";"))
    lines += [
        "",
        "on conflict (name) do update set",
        "  dept = excluded.dept,",
        "  collection = excluded.collection,",
        "  description = excluded.description,",
        "  price_ghs = excluded.price_ghs,",
        "  compare_at_ghs = excluded.compare_at_ghs,",
        "  flash_sale = excluded.flash_sale,",
        "  sizes = excluded.sizes,",
        "  colors = excluded.colors,",
        "  badge = excluded.badge,",
        "  in_stock = excluded.in_stock,",
        "  sort_order = excluded.sort_order,",
        "  image = excluded.image;",
        "",
        "-- Keep the identity sequence ahead of the explicit ids above.",
        "select setval(",
        "  pg_get_serial_sequence('public.products', 'id'),",
        "  coalesce((select max(id) from public.products), 1)",
        ");",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    content = render_seed()
    if "--check" in sys.argv:
        if not SEED_PATH.exists():
            raise SystemExit("FAIL: supabase/catalog-seed.sql does not exist. Run the generator.")
        current = SEED_PATH.read_text()
        if current != content:
            raise SystemExit(
                "FAIL: supabase/catalog-seed.sql is out of date with js/catalog.js.\n"
                "Run: python3 scripts/generate_catalog_seed.py"
            )
        print("OK: catalog-seed.sql matches js/catalog.js")
        return
    SEED_PATH.parent.mkdir(parents=True, exist_ok=True)
    SEED_PATH.write_text(content)
    print(f"wrote {SEED_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
